export type MermaidTemplateType =
  | "flowchart"
  | "sequence"
  | "class"
  | "state"
  | "er"
  | "journey"
  | "gantt"
  | "pie"
  | "gitgraph"
  | "mindmap"
  | "timeline"
  | "quadrant"
  | "architecture"
  | "block";

export interface MermaidTemplateTypeOption {
  type: MermaidTemplateType;
  commandId: string;
  label: string;
  description: string;
}

export interface MermaidTemplateDefinition {
  id: string;
  type: MermaidTemplateType;
  title: string;
  description: string;
  markdown: string;
}

function buildMermaidMarkdown(lines: string[]): string {
  return ["```mermaid", ...lines, "```"].join("\n");
}

export const MERMAID_TEMPLATE_TYPES: MermaidTemplateTypeOption[] = [
  {
    type: "flowchart",
    commandId: "flowchart",
    label: "Flowchart",
    description: "Boxes and arrows for process steps.",
  },
  {
    type: "sequence",
    commandId: "sequence",
    label: "Sequence",
    description: "Messages between people or systems.",
  },
  {
    type: "class",
    commandId: "class",
    label: "Class",
    description: "Objects, fields, and relationships.",
  },
  {
    type: "state",
    commandId: "state",
    label: "State",
    description: "Status changes over time.",
  },
  {
    type: "er",
    commandId: "er",
    label: "ER Diagram",
    description: "Tables and database relationships.",
  },
  {
    type: "journey",
    commandId: "journey",
    label: "Journey",
    description: "Steps in a user experience.",
  },
  {
    type: "gantt",
    commandId: "gantt",
    label: "Gantt",
    description: "Tasks on a timeline.",
  },
  {
    type: "pie",
    commandId: "pie",
    label: "Pie",
    description: "Simple part-of-whole chart.",
  },
  {
    type: "gitgraph",
    commandId: "gitgraph",
    label: "Git Graph",
    description: "Branches, commits, and merges.",
  },
  {
    type: "mindmap",
    commandId: "mindmap",
    label: "Mindmap",
    description: "Ideas branching from one topic.",
  },
  {
    type: "timeline",
    commandId: "timeline",
    label: "Timeline",
    description: "Events in chronological order.",
  },
  {
    type: "quadrant",
    commandId: "quadrant",
    label: "Quadrant",
    description: "Plot ideas on two axes.",
  },
  {
    type: "architecture",
    commandId: "architecture",
    label: "Architecture",
    description: "High-level system parts and links.",
  },
  {
    type: "block",
    commandId: "block",
    label: "Block Diagram",
    description: "Simple grouped system blocks.",
  },
];

export const MERMAID_TEMPLATES: MermaidTemplateDefinition[] = [
  {
    id: "flowchart-basic",
    type: "flowchart",
    title: "Basic Process",
    description: "Start, decision, next step, and finish.",
    markdown: buildMermaidMarkdown([
      "flowchart TD",
      "  A[Start] --> B{Decision}",
      "  B -->|Yes| C[Do the work]",
      "  B -->|No| D[Review again]",
      "  C --> E[Finish]",
      "  D --> E",
    ]),
  },
  {
    id: "flowchart-lanes",
    type: "flowchart",
    title: "Team Handoff",
    description: "Show work moving between groups.",
    markdown: buildMermaidMarkdown([
      "flowchart LR",
      "  subgraph Product",
      "    A[Define scope]",
      "    B[Approve plan]",
      "  end",
      "  subgraph Engineering",
      "    C[Build feature]",
      "    D[Test changes]",
      "  end",
      "  subgraph Release",
      "    E[Ship update]",
      "  end",
      "  A --> B --> C --> D --> E",
    ]),
  },
  {
    id: "sequence-request",
    type: "sequence",
    title: "Request Cycle",
    description: "User request, app work, and response.",
    markdown: buildMermaidMarkdown([
      "sequenceDiagram",
      "  participant U as User",
      "  participant A as App",
      "  participant S as Service",
      "  U->>A: Start action",
      "  A->>S: Send request",
      "  S-->>A: Return result",
      "  A-->>U: Show update",
    ]),
  },
  {
    id: "sequence-auth",
    type: "sequence",
    title: "Sign In",
    description: "A simple authentication flow.",
    markdown: buildMermaidMarkdown([
      "sequenceDiagram",
      "  participant U as User",
      "  participant W as Web App",
      "  participant I as Identity Provider",
      "  U->>W: Open sign in",
      "  W->>I: Redirect for login",
      "  I-->>U: Ask for credentials",
      "  U->>I: Submit credentials",
      "  I-->>W: Return token",
      "  W-->>U: Signed in",
    ]),
  },
  {
    id: "class-domain",
    type: "class",
    title: "Domain Model",
    description: "Common entity relationships.",
    markdown: buildMermaidMarkdown([
      "classDiagram",
      "  class Project {",
      "    +String name",
      "    +String status",
      "  }",
      "  class Task {",
      "    +String title",
      "    +Boolean done",
      "  }",
      "  class Person {",
      "    +String name",
      "  }",
      "  Project \"1\" --> \"many\" Task : contains",
      "  Person \"1\" --> \"many\" Task : owns",
    ]),
  },
  {
    id: "class-service",
    type: "class",
    title: "Service Layer",
    description: "Controller, service, and store example.",
    markdown: buildMermaidMarkdown([
      "classDiagram",
      "  class ThreadNoteDrawer",
      "  class ThreadNoteService {",
      "    +save(text)",
      "    +load(threadId)",
      "  }",
      "  class ConversationStore {",
      "    +saveThreadNote(threadId, noteId, text)",
      "  }",
      "  ThreadNoteDrawer --> ThreadNoteService",
      "  ThreadNoteService --> ConversationStore",
    ]),
  },
  {
    id: "state-simple",
    type: "state",
    title: "Simple Lifecycle",
    description: "Idle to running to done.",
    markdown: buildMermaidMarkdown([
      "stateDiagram-v2",
      "  [*] --> Idle",
      "  Idle --> Editing : start",
      "  Editing --> Saving : save",
      "  Saving --> Editing : saved",
      "  Editing --> Preview : switch view",
      "  Preview --> Editing : edit more",
      "  Preview --> [*] : close",
    ]),
  },
  {
    id: "state-review",
    type: "state",
    title: "Review Process",
    description: "Draft, review, revision, and approval.",
    markdown: buildMermaidMarkdown([
      "stateDiagram-v2",
      "  [*] --> Draft",
      "  Draft --> InReview : submit",
      "  InReview --> ChangesNeeded : feedback",
      "  ChangesNeeded --> Draft : revise",
      "  InReview --> Approved : approve",
      "  Approved --> Released : ship",
      "  Released --> [*]",
    ]),
  },
  {
    id: "er-project",
    type: "er",
    title: "Project Data",
    description: "Projects, notes, and sessions.",
    markdown: buildMermaidMarkdown([
      "erDiagram",
      "  PROJECT ||--o{ THREAD : contains",
      "  THREAD ||--o{ NOTE : stores",
      "  THREAD ||--o{ MESSAGE : records",
      "  PROJECT {",
      "    string id",
      "    string name",
      "  }",
      "  NOTE {",
      "    string id",
      "    string title",
      "  }",
    ]),
  },
  {
    id: "er-commerce",
    type: "er",
    title: "Order Data",
    description: "Customer, order, and item example.",
    markdown: buildMermaidMarkdown([
      "erDiagram",
      "  CUSTOMER ||--o{ ORDER : places",
      "  ORDER ||--|{ ORDER_ITEM : includes",
      "  PRODUCT ||--o{ ORDER_ITEM : appears_in",
      "  CUSTOMER {",
      "    string id",
      "    string email",
      "  }",
      "  ORDER {",
      "    string id",
      "    date created_at",
      "  }",
    ]),
  },
  {
    id: "journey-onboarding",
    type: "journey",
    title: "Onboarding Journey",
    description: "Track feeling across a new-user flow.",
    markdown: buildMermaidMarkdown([
      "journey",
      "  title New User Setup",
      "  section Discover",
      "    Find the feature: 4: User",
      "    Read quick help: 5: User",
      "  section Start",
      "    Create first note: 4: User",
      "    Add Mermaid chart: 5: User",
      "  section Finish",
      "    Save and revisit: 4: User",
    ]),
  },
  {
    id: "journey-support",
    type: "journey",
    title: "Support Journey",
    description: "Show pain points in support steps.",
    markdown: buildMermaidMarkdown([
      "journey",
      "  title Customer Support",
      "  section Report",
      "    Open help ticket: 2: Customer",
      "    Add screenshots: 3: Customer",
      "  section Resolve",
      "    Review issue: 4: Support",
      "    Send fix: 5: Support",
      "  section Close",
      "    Confirm solved: 5: Customer",
    ]),
  },
  {
    id: "gantt-release",
    type: "gantt",
    title: "Release Plan",
    description: "A short delivery schedule.",
    markdown: buildMermaidMarkdown([
      "gantt",
      "  title Release Plan",
      "  dateFormat  YYYY-MM-DD",
      "  section Build",
      "  Scope feature      :done,    t1, 2026-03-29, 2d",
      "  Implement UI       :active,  t2, after t1, 3d",
      "  section Validate",
      "  QA review          :         t3, after t2, 2d",
      "  Ship release       :milestone, t4, after t3, 1d",
    ]),
  },
  {
    id: "gantt-roadmap",
    type: "gantt",
    title: "Mini Roadmap",
    description: "Plan several phases in order.",
    markdown: buildMermaidMarkdown([
      "gantt",
      "  title Product Roadmap",
      "  dateFormat  YYYY-MM-DD",
      "  section Phase 1",
      "  Research           :done, p1, 2026-04-01, 4d",
      "  section Phase 2",
      "  Prototype          :active, p2, after p1, 5d",
      "  section Phase 3",
      "  Launch             :p3, after p2, 3d",
    ]),
  },
  {
    id: "pie-breakdown",
    type: "pie",
    title: "Simple Breakdown",
    description: "Show a few parts of a whole.",
    markdown: buildMermaidMarkdown([
      "pie title Weekly Focus",
      '  "Feature work" : 45',
      '  "Bug fixes" : 20',
      '  "Meetings" : 15',
      '  "Planning" : 20',
    ]),
  },
  {
    id: "pie-usage",
    type: "pie",
    title: "Usage Mix",
    description: "Compare several feature areas.",
    markdown: buildMermaidMarkdown([
      "pie title Feature Usage",
      '  "Notes" : 35',
      '  "Chat" : 30',
      '  "Automations" : 15',
      '  "Settings" : 20',
    ]),
  },
  {
    id: "gitgraph-feature",
    type: "gitgraph",
    title: "Feature Branch",
    description: "A basic branch and merge flow.",
    markdown: buildMermaidMarkdown([
      "gitGraph",
      "  commit id: \"init\"",
      "  branch feature",
      "  checkout feature",
      "  commit id: \"ui\"",
      "  commit id: \"tests\"",
      "  checkout main",
      "  merge feature",
      "  commit id: \"release\"",
    ]),
  },
  {
    id: "gitgraph-hotfix",
    type: "gitgraph",
    title: "Hotfix Flow",
    description: "Release, patch, and merge back.",
    markdown: buildMermaidMarkdown([
      "gitGraph",
      "  commit id: \"v1\"",
      "  branch release",
      "  checkout release",
      "  commit id: \"prepare\"",
      "  branch hotfix",
      "  checkout hotfix",
      "  commit id: \"fix\"",
      "  checkout main",
      "  merge hotfix",
      "  checkout release",
      "  merge hotfix",
    ]),
  },
  {
    id: "mindmap-topic",
    type: "mindmap",
    title: "Idea Map",
    description: "Break one topic into smaller ideas.",
    markdown: buildMermaidMarkdown([
      "mindmap",
      "  root((Launch))",
      "    Product",
      "      Scope",
      "      Messaging",
      "    Engineering",
      "      UI",
      "      Backend",
      "    Growth",
      "      Docs",
      "      Demo",
    ]),
  },
  {
    id: "mindmap-study",
    type: "mindmap",
    title: "Study Notes",
    description: "Organize a topic and subtopics.",
    markdown: buildMermaidMarkdown([
      "mindmap",
      "  root((Mermaid))",
      "    Flowcharts",
      "      Nodes",
      "      Links",
      "    Sequence",
      "      Actors",
      "      Messages",
      "    Planning",
      "      Notes",
      "      Templates",
    ]),
  },
  {
    id: "timeline-project",
    type: "timeline",
    title: "Project History",
    description: "Show key milestones over time.",
    markdown: buildMermaidMarkdown([
      "timeline",
      "  title Project Milestones",
      "  2026-01 : Kickoff",
      "          : Research complete",
      "  2026-02 : Prototype ready",
      "  2026-03 : Testing round",
      "  2026-04 : Public launch",
    ]),
  },
  {
    id: "timeline-company",
    type: "timeline",
    title: "Release Story",
    description: "A simple event history.",
    markdown: buildMermaidMarkdown([
      "timeline",
      "  title Release Story",
      "  Week 1 : Idea approved",
      "  Week 2 : UI built",
      "  Week 3 : Feedback collected",
      "  Week 4 : Fixes shipped",
    ]),
  },
  {
    id: "quadrant-priority",
    type: "quadrant",
    title: "Priority Matrix",
    description: "Compare impact and effort.",
    markdown: buildMermaidMarkdown([
      "quadrantChart",
      "  title Prioritize Work",
      "  x-axis Low Effort --> High Effort",
      "  y-axis Low Impact --> High Impact",
      "  quadrant-1 Quick Wins",
      "  quadrant-2 Big Bets",
      "  quadrant-3 Low Value",
      "  quadrant-4 Hard Sells",
      "  UI polish: [0.25, 0.65]",
      "  Mermaid templates: [0.45, 0.88]",
      "  Large migration: [0.78, 0.7]",
      "  Remove docs: [0.15, 0.2]",
    ]),
  },
  {
    id: "quadrant-risk",
    type: "quadrant",
    title: "Risk Matrix",
    description: "Compare likelihood and severity.",
    markdown: buildMermaidMarkdown([
      "quadrantChart",
      "  title Risk Review",
      "  x-axis Unlikely --> Likely",
      "  y-axis Low Severity --> High Severity",
      "  quadrant-1 Watch",
      "  quadrant-2 Critical",
      "  quadrant-3 Minor",
      "  quadrant-4 Annoying",
      "  Build warning: [0.32, 0.48]",
      "  Data loss: [0.72, 0.96]",
      "  Styling bug: [0.64, 0.3]",
      "  Typo: [0.14, 0.08]",
    ]),
  },
  {
    id: "architecture-app",
    type: "architecture",
    title: "App Overview",
    description: "Show a few connected services.",
    markdown: buildMermaidMarkdown([
      "architecture-beta",
      "  group client(cloud)[Client]",
      "  service ui(server)[UI] in client",
      "  service notes(database)[Notes Store] in client",
      "  group platform(cloud)[Platform]",
      "  service api(server)[API] in platform",
      "  service model(disk)[Model] in platform",
      "  ui:R --> L:api",
      "  api:B --> T:model",
      "  ui:B --> T:notes",
    ]),
  },
  {
    id: "architecture-pipeline",
    type: "architecture",
    title: "Delivery Path",
    description: "Browser, app, and backend pieces.",
    markdown: buildMermaidMarkdown([
      "architecture-beta",
      "  group user(cloud)[User]",
      "  service browser(internet)[Browser] in user",
      "  group app(cloud)[Application]",
      "  service web(server)[Web UI] in app",
      "  service worker(server)[Worker] in app",
      "  service store(database)[Storage] in app",
      "  browser:R --> L:web",
      "  web:B --> T:worker",
      "  worker:R --> L:store",
    ]),
  },
  {
    id: "block-system",
    type: "block",
    title: "System Blocks",
    description: "A few connected functional areas.",
    markdown: buildMermaidMarkdown([
      "block-beta",
      "  columns 3",
      "  block:input:2",
      "    Input",
      "  end",
      "  block:logic:1",
      "    Logic",
      "  end",
      "  block:output:3",
      "    Output",
      "  end",
      "  input --> logic --> output",
    ]),
  },
  {
    id: "block-layers",
    type: "block",
    title: "Layered Stack",
    description: "Display a simple app stack.",
    markdown: buildMermaidMarkdown([
      "block-beta",
      "  columns 1",
      "  block:ui",
      "    UI Layer",
      "  end",
      "  block:service",
      "    Service Layer",
      "  end",
      "  block:data",
      "    Data Layer",
      "  end",
      "  ui --> service --> data",
    ]),
  },
];

export function mermaidTemplatesForType(
  type: MermaidTemplateType
): MermaidTemplateDefinition[] {
  return MERMAID_TEMPLATES.filter((template) => template.type === type);
}
