import AppKit
import Foundation

let eventPostDelay: useconds_t = 1_500
let finalDeliveryDelay: useconds_t = 30_000
let clipboardRestoreDelay: useconds_t = 450_000
let transientPasteboardTypes: [NSPasteboard.PasteboardType] = [
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
]
let openAssistTransientMarkerType = NSPasteboard.PasteboardType("com.openassist.transient-marker")

enum HelperError: Error, CustomStringConvertible {
    case missingArgument(String)
    case unreadableText(String)
    case eventSourceUnavailable
    case eventCreationFailed

    var description: String {
        switch self {
        case .missingArgument(let message):
            return message
        case .unreadableText(let message):
            return message
        case .eventSourceUnavailable:
            return "Could not create a keyboard event source."
        case .eventCreationFailed:
            return "Could not create a keyboard event."
        }
    }
}

struct Arguments {
    let strategy: String
    let textPath: String
}

func parseArguments() throws -> Arguments {
    let args = CommandLine.arguments.dropFirst()
    var strategy = "unicode-events"
    var textPath: String?
    var iterator = args.makeIterator()

    while let arg = iterator.next() {
        switch arg {
        case "--strategy":
            strategy = iterator.next() ?? strategy
        case "--text-file":
            textPath = iterator.next()
        default:
            continue
        }
    }

    guard let textPath else {
        throw HelperError.missingArgument("Missing --text-file argument.")
    }

    return Arguments(strategy: strategy, textPath: textPath)
}

func readText(at path: String) throws -> String {
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else {
        throw HelperError.unreadableText("Could not read transcript text.")
    }
    return text
}

func postKeyCode(_ keyCode: CGKeyCode, source: CGEventSource) throws {
    guard
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
    else {
        throw HelperError.eventCreationFailed
    }
    keyDown.post(tap: .cgSessionEventTap)
    keyUp.post(tap: .cgSessionEventTap)
    usleep(eventPostDelay)
}

func insertByUnicodeEvents(_ text: String) throws {
    guard let source = CGEventSource(stateID: .combinedSessionState) ?? CGEventSource(stateID: .hidSystemState) else {
        throw HelperError.eventSourceUnavailable
    }

    for scalar in text.unicodeScalars {
        switch scalar.value {
        case 10:
            try postKeyCode(36, source: source)
        case 9:
            try postKeyCode(48, source: source)
        default:
            var utf16Units = Array(String(scalar).utf16)
            guard
                let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true),
                let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
            else {
                throw HelperError.eventCreationFailed
            }

            keyDown.keyboardSetUnicodeString(stringLength: utf16Units.count, unicodeString: &utf16Units)
            keyUp.keyboardSetUnicodeString(stringLength: utf16Units.count, unicodeString: &utf16Units)
            keyDown.post(tap: .cgSessionEventTap)
            keyUp.post(tap: .cgSessionEventTap)
            usleep(eventPostDelay)
        }
    }

    usleep(finalDeliveryDelay)
}

func appleScriptEscaped(_ value: String) -> String {
    value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
}

func runAppleScript(_ source: String) -> Bool {
    let script = NSAppleScript(source: source)
    var error: NSDictionary?
    script?.executeAndReturnError(&error)
    return error == nil
}

func insertByAppleScriptKeystroke(_ text: String) -> Bool {
    let normalized = text
        .replacingOccurrences(of: "\r\n", with: "\n")
        .replacingOccurrences(of: "\r", with: "\n")
    var currentChunk = ""

    func flushChunk() -> Bool {
        guard !currentChunk.isEmpty else { return true }
        let escaped = appleScriptEscaped(currentChunk)
        let ok = runAppleScript("""
            tell application "System Events"
                keystroke "\(escaped)"
            end tell
            """)
        currentChunk = ""
        return ok
    }

    func sendSpecialKeyCode(_ keyCode: Int) -> Bool {
        runAppleScript("""
            tell application "System Events"
                key code \(keyCode)
            end tell
            """)
    }

    for scalar in normalized.unicodeScalars {
        switch scalar.value {
        case 10:
            guard flushChunk(), sendSpecialKeyCode(36) else { return false }
        case 9:
            guard flushChunk(), sendSpecialKeyCode(48) else { return false }
        default:
            currentChunk.unicodeScalars.append(scalar)
            if currentChunk.count >= 48, !flushChunk() {
                return false
            }
        }
    }

    return flushChunk()
}

func stringAttributeValue(for element: AXUIElement, attribute: CFString) -> String? {
    var valueRef: CFTypeRef?
    let result = AXUIElementCopyAttributeValue(element, attribute, &valueRef)
    guard result == .success, let value = valueRef as? String else {
        return nil
    }
    return value
}

func valueByRemovingPlaceholderArtifacts(_ value: String, placeholderValue: String?) -> String {
    guard let placeholderValue = placeholderValue?.trimmingCharacters(in: .whitespacesAndNewlines),
          !placeholderValue.isEmpty else {
        return value
    }

    if value == placeholderValue {
        return ""
    }

    for suffix in [placeholderValue, " " + placeholderValue, "\n" + placeholderValue, "\t" + placeholderValue] where value.hasSuffix(suffix) {
        return String(value.dropLast(suffix.count))
    }

    for prefix in [placeholderValue, placeholderValue + " ", placeholderValue + "\n", placeholderValue + "\t"] where value.hasPrefix(prefix) {
        return String(value.dropFirst(prefix.count))
    }

    return value
}

func focusedTextElement() -> AXUIElement? {
    let systemWide = AXUIElementCreateSystemWide()
    var focusedRef: CFTypeRef?
    let focusedResult = AXUIElementCopyAttributeValue(
        systemWide,
        kAXFocusedUIElementAttribute as CFString,
        &focusedRef
    )
    guard focusedResult == .success, let focusedRef else {
        return nil
    }

    guard CFGetTypeID(focusedRef) == AXUIElementGetTypeID() else {
        return nil
    }

    return unsafeBitCast(focusedRef, to: AXUIElement.self)
}

func insertDirectlyIntoFocusedTextInput(_ text: String) -> Bool {
    guard let focusedElement = focusedTextElement() else {
        return false
    }

    guard let rawCurrentValue = stringAttributeValue(for: focusedElement, attribute: kAXValueAttribute as CFString) else {
        return false
    }
    let placeholderValue = stringAttributeValue(for: focusedElement, attribute: kAXPlaceholderValueAttribute as CFString)
    let currentValue = valueByRemovingPlaceholderArtifacts(rawCurrentValue, placeholderValue: placeholderValue)

    var selectedRangeRef: CFTypeRef?
    let rangeResult = AXUIElementCopyAttributeValue(
        focusedElement,
        kAXSelectedTextRangeAttribute as CFString,
        &selectedRangeRef
    )
    guard rangeResult == .success, let selectedRangeRef else {
        return false
    }

    guard CFGetTypeID(selectedRangeRef) == AXValueGetTypeID() else {
        return false
    }

    let selectedRangeAX = unsafeBitCast(selectedRangeRef, to: AXValue.self)
    guard AXValueGetType(selectedRangeAX) == .cfRange else {
        return false
    }

    var selectedRange = CFRange(location: 0, length: 0)
    guard AXValueGetValue(selectedRangeAX, .cfRange, &selectedRange) else {
        return false
    }

    let currentNSString = currentValue as NSString
    let safeLocation = max(0, min(selectedRange.location, currentNSString.length))
    let safeLength = max(0, min(selectedRange.length, currentNSString.length - safeLocation))
    let replacementRange = NSRange(location: safeLocation, length: safeLength)
    let updatedValue = currentNSString.replacingCharacters(in: replacementRange, with: text)

    let setValueResult = AXUIElementSetAttributeValue(
        focusedElement,
        kAXValueAttribute as CFString,
        updatedValue as CFTypeRef
    )
    guard setValueResult == .success else {
        return false
    }

    if let verifiedValue = stringAttributeValue(for: focusedElement, attribute: kAXValueAttribute as CFString) {
        let normalizedVerifiedValue = valueByRemovingPlaceholderArtifacts(verifiedValue, placeholderValue: placeholderValue)
        if normalizedVerifiedValue == currentValue {
            return false
        }
    }

    var newSelection = CFRange(location: safeLocation + (text as NSString).length, length: 0)
    if let newSelectionAX = AXValueCreate(.cfRange, &newSelection) {
        _ = AXUIElementSetAttributeValue(
            focusedElement,
            kAXSelectedTextRangeAttribute as CFString,
            newSelectionAX
        )
    }

    return true
}

struct ClipboardSnapshotItem {
    let types: [NSPasteboard.PasteboardType]
    let dataByType: [NSPasteboard.PasteboardType: Data]
}

func captureClipboardSnapshot() -> [ClipboardSnapshotItem] {
    NSPasteboard.general.pasteboardItems?.compactMap { item in
        var dataByType: [NSPasteboard.PasteboardType: Data] = [:]
        for type in item.types {
            if let data = item.data(forType: type) {
                dataByType[type] = data
            }
        }
        return dataByType.isEmpty ? nil : ClipboardSnapshotItem(types: item.types, dataByType: dataByType)
    } ?? []
}

func pasteboardContainsTransientMarker(_ pasteboard: NSPasteboard) -> Bool {
    pasteboard.pasteboardItems?.contains { item in
        item.availableType(from: [openAssistTransientMarkerType]) != nil
    } ?? false
}

func restoreClipboardSnapshot(_ snapshot: [ClipboardSnapshotItem], expectedChangeCount: Int) {
    let pasteboard = NSPasteboard.general
    usleep(clipboardRestoreDelay)

    guard pasteboard.changeCount == expectedChangeCount || pasteboardContainsTransientMarker(pasteboard) else {
        return
    }

    pasteboard.clearContents()
    let restoredItems = snapshot.compactMap { snapshotItem -> NSPasteboardItem? in
        let item = NSPasteboardItem()
        var wroteAny = false
        for type in snapshotItem.types {
            if let data = snapshotItem.dataByType[type] {
                item.setData(data, forType: type)
                wroteAny = true
            }
        }
        return wroteAny ? item : nil
    }
    if !restoredItems.isEmpty {
        pasteboard.writeObjects(restoredItems)
    }
}

func writeTransientClipboard(_ text: String) -> Int? {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    let item = NSPasteboardItem()
    item.setString(text, forType: .string)
    for type in transientPasteboardTypes {
        item.setString("", forType: type)
    }
    item.setString("1", forType: openAssistTransientMarkerType)
    guard pasteboard.writeObjects([item]) else {
        return nil
    }
    guard pasteboard.string(forType: .string) == text else {
        return nil
    }
    return pasteboard.changeCount
}

func sendPasteViaMenuItemAppleScript() -> Bool {
    runAppleScript("""
        tell application "System Events"
            tell first application process whose frontmost is true
                click menu item "Paste" of menu 1 of menu bar item "Edit" of menu bar 1
            end tell
        end tell
        """)
}

func sendPasteViaAppleScriptKeystroke() -> Bool {
    runAppleScript("""
        tell application "System Events"
            keystroke "v" using command down
        end tell
        """)
}

func sendPasteViaCGEvent() -> Bool {
    guard let source = CGEventSource(stateID: .combinedSessionState) ?? CGEventSource(stateID: .hidSystemState) else {
        return false
    }

    let commandKeyCode: CGKeyCode = 55
    let vKeyV: CGKeyCode = 9

    guard
        let commandDown = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: true),
        let commandUp = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: false),
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyV, keyDown: true),
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyV, keyDown: false)
    else {
        return false
    }

    usleep(30_000)
    commandDown.post(tap: .cgSessionEventTap)
    usleep(4_000)
    keyDown.flags = [.maskCommand]
    keyDown.post(tap: .cgSessionEventTap)
    keyUp.flags = [.maskCommand]
    keyUp.post(tap: .cgSessionEventTap)
    usleep(4_000)
    commandUp.post(tap: .cgSessionEventTap)
    usleep(10_000)
    return true
}

func triggerPasteShortcutWithRetry() -> Bool {
    for delay in [0, 40_000, 100_000] as [useconds_t] {
        if delay > 0 {
            usleep(delay)
        }
        if sendPasteViaMenuItemAppleScript() || sendPasteViaAppleScriptKeystroke() || sendPasteViaCGEvent() {
            return true
        }
    }
    return false
}

func insertByTransientPaste(_ text: String) -> Bool {
    let snapshot = captureClipboardSnapshot()
    guard let expectedChangeCount = writeTransientClipboard(text) else {
        return false
    }
    let didPaste = triggerPasteShortcutWithRetry()
    restoreClipboardSnapshot(snapshot, expectedChangeCount: expectedChangeCount)
    return didPaste
}

func finish(ok: Bool, method: String, error: String? = nil) -> Never {
    let payload: [String: Any] = [
        "ok": ok,
        "method": method,
        "error": error ?? ""
    ]
    let data = try? JSONSerialization.data(withJSONObject: payload, options: [])
    if let data, let json = String(data: data, encoding: .utf8) {
        print(json)
    }
    exit(ok ? 0 : 1)
}

do {
    let arguments = try parseArguments()
    let text = try readText(at: arguments.textPath)
    if arguments.strategy == "accessibility-direct-preferred" {
        if insertDirectlyIntoFocusedTextInput(text) {
            finish(ok: true, method: "accessibility-direct")
        }
        finish(ok: false, method: "accessibility-direct", error: "Focused text field was not writable through Accessibility.")
    }
    if arguments.strategy == "transient-paste" {
        if insertByTransientPaste(text) {
            finish(ok: true, method: "transient-paste")
        }
        finish(ok: false, method: "transient-paste", error: "Could not paste into the focused app.")
    }
    if arguments.strategy == "applescript-keystroke-preferred" {
        if insertByAppleScriptKeystroke(text) {
            finish(ok: true, method: "applescript-keystroke")
        }
        try insertByUnicodeEvents(text)
        finish(ok: true, method: "unicode-events")
    }

    try insertByUnicodeEvents(text)
    finish(ok: true, method: "unicode-events")
} catch {
    finish(ok: false, method: "none", error: String(describing: error))
}
