export type SettingsSection = {
  id: string;
  title: string;
  subtitle: string;
  /**
   * Free-text keywords covering the controls, features, and field labels that
   * live inside this section. The settings search matches against these in
   * addition to the title/subtitle so users can find a specific setting by the
   * word they actually have in mind (e.g. "wake word", "ollama", "api key").
   */
  keywords: string[];
};

export const settingsSections: SettingsSection[] = [
  {
    id: "assistant",
    title: "Assistant",
    subtitle: "Assistant window behavior, sidebar mode, and code tracking.",
    keywords: [
      "assistant",
      "window",
      "sidebar",
      "notch",
      "compact",
      "edge",
      "left",
      "right",
      "code tracking",
      "git",
      "repositories",
      "knowledge",
      "access",
      "notes",
      "today",
      "planner",
      "journal",
      "tasks",
      "agent",
      "realtime voice",
      "external",
      "integrations",
      "mcp",
      "cursor",
      "codex",
      "claude",
      "skill"
    ]
  },
  {
    id: "voice",
    title: "Voice & Dictation",
    subtitle: "Microphone input, transcription, and correction quality.",
    keywords: [
      "voice",
      "dictation",
      "microphone",
      "mic",
      "input device",
      "auto detect",
      "live voice",
      "realtime",
      "openai realtime",
      "gemini live",
      "local voice agent",
      "delegation",
      "wake word",
      "hey open assist",
      "phrase",
      "audio feedback",
      "sound",
      "cue",
      "volume",
      "transcription",
      "speech to text",
      "stt",
      "apple speech",
      "whisper",
      "whisper.cpp",
      "coreml",
      "cloud",
      "transcription engine",
      "model",
      "base url",
      "api key",
      "correction",
      "filler words",
      "adaptive",
      "voice reply",
      "read aloud",
      "tts",
      "text to speech",
      "openai tts",
      "gemini tts",
      "pocket",
      "kokoro",
      "macos voice",
      "waveform"
    ]
  },
  {
    id: "shortcuts",
    title: "Keyboard Shortcuts",
    subtitle: "One place for dictation, assistant, sidebar, and screen-analysis hotkeys.",
    keywords: [
      "shortcuts",
      "keyboard",
      "hotkeys",
      "keybindings",
      "hold to talk",
      "continuous",
      "toggle",
      "live voice",
      "assistant",
      "sidebar",
      "compact",
      "screen analysis",
      "snip"
    ]
  },
  {
    id: "models",
    title: "Models & Connections",
    subtitle: "Chat runtimes, model readouts, and prompt rewrite provider keys.",
    keywords: [
      "models",
      "connections",
      "runtimes",
      "chat runtime",
      "provider",
      "codex",
      "chatgpt",
      "ollama",
      "claude",
      "gemini",
      "grok",
      "model",
      "sub agent",
      "account",
      "authentication",
      "login",
      "install",
      "download",
      "server",
      "catalog",
      "note ai",
      "note cleanup",
      "reasoning",
      "prompt rewrite",
      "rewrite",
      "base url",
      "api key"
    ]
  },
  {
    id: "automation",
    title: "Automation & Remote",
    subtitle: "Computer Use, local helper API, Telegram, and remote access.",
    keywords: [
      "automation",
      "remote",
      "computer use",
      "browser",
      "profile",
      "app control",
      "helper",
      "local api",
      "api helper",
      "port",
      "logs",
      "telegram",
      "bot",
      "token",
      "botfather",
      "chat",
      "session",
      "pairing",
      "remote access",
      "pair",
      "device",
      "qr",
      "easy qr",
      "tunnel",
      "tailscale",
      "pairing code",
      "pairing url",
      "server"
    ]
  },
  {
    id: "connectors",
    title: "Connectors",
    subtitle: "Bring Gmail, Google, Apple, Notes, and Messages into Today and Backlog.",
    keywords: [
      "connectors",
      "gmail",
      "google",
      "gws",
      "account",
      "oauth",
      "client",
      "consent",
      "sync",
      "login",
      "calendar",
      "reminders",
      "notes",
      "messages",
      "apple",
      "eventkit",
      "full disk access",
      "local sources",
      "review",
      "inbox"
    ]
  },
  {
    id: "appearance",
    title: "Appearance",
    subtitle: "Theme mode, color themes, fonts, motion, and visual effects.",
    keywords: [
      "appearance",
      "theme",
      "light",
      "dark",
      "system",
      "color theme",
      "ocean",
      "violet",
      "midnight",
      "slate",
      "forest",
      "rose",
      "accent",
      "background",
      "foreground",
      "custom theme",
      "fonts",
      "font size",
      "ui font",
      "code font",
      "font smoothing",
      "pointer cursors",
      "reduce motion",
      "interface style",
      "liquid glass",
      "classic",
      "waveform",
      "glow",
      "snip",
      "screen snip",
      "realtime glow",
      "visual effects"
    ]
  },
  {
    id: "app",
    title: "App & Permissions",
    subtitle: "macOS permissions, diagnostics, app info, and local data.",
    keywords: [
      "app",
      "permissions",
      "macos",
      "accessibility",
      "screen recording",
      "microphone",
      "automation",
      "speech recognition",
      "diagnostics",
      "logs",
      "crash",
      "helper logs",
      "insertion",
      "telemetry",
      "app info",
      "version",
      "build",
      "local data",
      "storage",
      "cleanup",
      "junk",
      "retention",
      "generated images",
      "old backups",
      "support",
      "app data"
    ]
  }
];
