import AppKit
import Carbon
import OSLog

enum TextInserter {
    enum Result: String, Equatable {
        case pasted = "pasted"
        case copiedOnly = "copied-only"
        case notInserted = "not-inserted"
        case empty = "empty"
    }

    enum InsertionContext {
        case standard
        case dictation
    }

    enum InsertionPolicy: String, Equatable {
        case standard = "standard"
        case preferTypingFirst = "prefer-typing-first"
    }

    enum TypingStrategy: String, Equatable {
        case unicodeEvents = "unicode-events"
        case appleScriptKeystrokePreferred = "applescript-keystroke-preferred"
    }

    struct InsertOutcome: Equatable {
        let result: Result
        let debugStatus: String?
    }

    enum ClipboardWriteOutcome: Equatable {
        case success(changeCount: Int)
        case failure(debugStatus: String)
    }

    struct ClipboardSnapshot {
        struct Item {
            struct Representation {
                let type: NSPasteboard.PasteboardType
                let data: Data
            }

            let representations: [Representation]
        }

        fileprivate let items: [Item]

        init(items: [Item] = []) {
            self.items = items
        }
    }

    struct Runtime {
        var shouldTryDirectInsert: () -> Bool
        var insertDirect: (String) -> Bool
        var insertTyping: (String) -> Bool
        var writeClipboard: (String) -> ClipboardWriteOutcome
        var writeTransientClipboard: (String) -> ClipboardWriteOutcome
        var sendSpecialPaste: () -> Bool
        var captureClipboard: () -> ClipboardSnapshot
        var restoreClipboard: (ClipboardSnapshot, Int) -> Void
        var log: (String) -> Void
        var pasteRetryBackoff: [TimeInterval]

        init(
            shouldTryDirectInsert: @escaping () -> Bool = { true },
            insertDirect: @escaping (String) -> Bool,
            insertTyping: @escaping (String) -> Bool,
            writeClipboard: @escaping (String) -> ClipboardWriteOutcome,
            writeTransientClipboard: @escaping (String) -> ClipboardWriteOutcome = { _ in .failure(debugStatus: "transient-clipboard-unconfigured") },
            sendSpecialPaste: @escaping () -> Bool,
            captureClipboard: @escaping () -> ClipboardSnapshot = { ClipboardSnapshot() },
            restoreClipboard: @escaping (ClipboardSnapshot, Int) -> Void = { _, _ in },
            log: @escaping (String) -> Void = { _ in },
            pasteRetryBackoff: [TimeInterval] = [0, 0.04, 0.1]
        ) {
            self.shouldTryDirectInsert = shouldTryDirectInsert
            self.insertDirect = insertDirect
            self.insertTyping = insertTyping
            self.writeClipboard = writeClipboard
            self.writeTransientClipboard = writeTransientClipboard
            self.sendSpecialPaste = sendSpecialPaste
            self.captureClipboard = captureClipboard
            self.restoreClipboard = restoreClipboard
            self.log = log
            self.pasteRetryBackoff = pasteRetryBackoff
        }
    }

    @MainActor
    private(set) static var lastDebugStatus: String?

    private static let logger = Logger(subsystem: "OpenAssist", category: "TextInserter")
    private static let clipboardWriteRetryBackoff: [TimeInterval] = [0, 0.015, 0.05]
    private static let clipboardRestoreDelay: TimeInterval = 0.45
    private static let transientPasteboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]
    private static let openAssistTransientMarkerType = NSPasteboard.PasteboardType("com.openassist.transient-marker")

    @MainActor
    static func insert(
        _ text: String,
        copyToClipboard: Bool,
        insertionContext: InsertionContext = .standard
    ) -> Result {
        let typingStrategy = liveTypingStrategy(for: insertionContext)
        let outcome = performInsert(
            text,
            copyToClipboard: copyToClipboard,
            insertionPolicy: liveInsertionPolicy(for: insertionContext),
            runtime: makeLiveRuntime(typingStrategy: typingStrategy)
        )
        lastDebugStatus = outcome.debugStatus

        if let debugStatus = outcome.debugStatus, outcome.result != .pasted {
            logger.debug("Insertion finished as \(resultLabel(outcome.result), privacy: .public) [\(debugStatus, privacy: .public)]")
        }

        return outcome.result
    }

    // Test-only insertion entrypoint used by smoke tests to validate clipboard flow deterministically.
    static func insertForSmokeTests(
        _ text: String,
        copyToClipboard: Bool,
        insertionPolicy: InsertionPolicy = .standard,
        runtime: Runtime
    ) -> InsertOutcome {
        performInsert(
            text,
            copyToClipboard: copyToClipboard,
            insertionPolicy: insertionPolicy,
            runtime: runtime
        )
    }

    private static func debugLog(_ message: String) {
        let line = "\(ISO8601DateFormatter().string(from: Date())) \(message)\n"
        let url = URL(fileURLWithPath: "/tmp/openassist-paste-debug.log")
        if let handle = try? FileHandle(forWritingTo: url) {
            defer { try? handle.close() }
            _ = try? handle.seekToEnd()
            handle.write(Data(line.utf8))
        } else {
            try? Data(line.utf8).write(to: url, options: .atomic)
        }
    }

    private static func performInsert(
        _ text: String,
        copyToClipboard: Bool,
        insertionPolicy: InsertionPolicy,
        runtime: Runtime
    ) -> InsertOutcome {
        guard !text.isEmpty else { return InsertOutcome(result: .empty, debugStatus: nil) }

        debugLog(
            "performInsert: text=\(text.prefix(30))... copyToClipboard=\(copyToClipboard) policy=\(insertionPolicy.rawValue) AXTrusted=\(AXIsProcessTrusted())"
        )

        if insertionPolicy == .preferTypingFirst {
            debugLog("Direct insert SKIPPED by typing-first insertion policy")
        } else if runtime.shouldTryDirectInsert() {
            if runtime.insertDirect(text) {
                debugLog("Direct insert SUCCEEDED")
                if copyToClipboard {
                    if case let .failure(debugStatus) = runtime.writeClipboard(text) {
                        runtime.log("Direct insert succeeded but clipboard copy failed [\(debugStatus)]")
                    }
                }
                return InsertOutcome(result: .pasted, debugStatus: nil)
            }
            debugLog("Direct insert FAILED")
        } else {
            debugLog("Direct insert SKIPPED by app compatibility policy")
        }

        if insertionPolicy == .preferTypingFirst {
            debugLog("Trying typingPreferred path")
            return insertWithTypingPreferred(text, copyToClipboard: copyToClipboard, runtime: runtime)
        }

        if copyToClipboard {
            debugLog("Trying clipboardPreferred path")
            return insertWithClipboardPreferred(text, runtime: runtime)
        }

        debugLog("Trying transient clipboard preferred path")
        let transientOutcome = insertWithTransientClipboardFallback(text, runtime: runtime)
        if transientOutcome.result == .pasted {
            return transientOutcome
        }

        debugLog("Transient clipboard paste FAILED, trying typing fallback")
        if runtime.insertTyping(text) {
            debugLog("Typing insert SUCCEEDED")
            return InsertOutcome(result: .pasted, debugStatus: nil)
        }

        debugLog("Typing insert FAILED after transient clipboard failure")
        return InsertOutcome(result: .notInserted, debugStatus: transientOutcome.debugStatus ?? "typing-unavailable")
    }

    private static func insertWithTypingPreferred(
        _ text: String,
        copyToClipboard: Bool,
        runtime: Runtime
    ) -> InsertOutcome {
        if runtime.insertTyping(text) {
            debugLog("typingPreferred: typing SUCCEEDED")
            if copyToClipboard,
               case let .failure(debugStatus) = runtime.writeClipboard(text) {
                runtime.log("Typing insert succeeded but clipboard mirror failed [\(debugStatus)]")
            }
            return InsertOutcome(result: .pasted, debugStatus: nil)
        }

        debugLog("typingPreferred: typing FAILED")
        return InsertOutcome(result: .notInserted, debugStatus: "typing-unavailable")
    }

    private static func insertWithClipboardPreferred(_ text: String, runtime: Runtime) -> InsertOutcome {
        switch runtime.writeClipboard(text) {
        case let .failure(debugStatus):
            debugLog("clipboardPreferred: clipboard write FAILED [\(debugStatus)]")
            runtime.log("Clipboard write verification failed before paste [\(debugStatus)]")
            if runtime.insertTyping(text) {
                return InsertOutcome(result: .pasted, debugStatus: nil)
            }
            return InsertOutcome(result: .notInserted, debugStatus: debugStatus)

        case .success:
            debugLog("clipboardPreferred: clipboard write OK, triggering paste shortcut")
            if triggerPasteShortcutWithRetry(runtime: runtime) {
                debugLog("clipboardPreferred: paste shortcut SUCCEEDED")
                return InsertOutcome(result: .pasted, debugStatus: nil)
            }

            debugLog("clipboardPreferred: paste shortcut FAILED, trying typing")
            runtime.log("Special paste shortcut failed; attempting typing fallback")
            if runtime.insertTyping(text) {
                return InsertOutcome(result: .pasted, debugStatus: nil)
            }

            return InsertOutcome(result: .copiedOnly, debugStatus: "paste-shortcut-unavailable")
        }
    }

    private static func insertWithTransientClipboardFallback(_ text: String, runtime: Runtime) -> InsertOutcome {
        let snapshot = runtime.captureClipboard()

        switch runtime.writeTransientClipboard(text) {
        case let .failure(debugStatus):
            debugLog("transientFallback: clipboard write FAILED [\(debugStatus)]")
            runtime.log("Transient clipboard write verification failed [\(debugStatus)]")
            return InsertOutcome(result: .notInserted, debugStatus: debugStatus)

        case let .success(changeCount):
            debugLog("transientFallback: clipboard write OK, triggering paste shortcut")
            if triggerPasteShortcutWithRetry(runtime: runtime) {
                debugLog("transientFallback: paste shortcut SUCCEEDED, restoring clipboard snapshot")
                runtime.restoreClipboard(snapshot, changeCount)
                return InsertOutcome(result: .pasted, debugStatus: nil)
            }

            debugLog("transientFallback: paste shortcut FAILED, restoring clipboard snapshot")
            runtime.restoreClipboard(snapshot, changeCount)
            return InsertOutcome(result: .notInserted, debugStatus: "paste-shortcut-unavailable")
        }
    }

    private static func triggerPasteShortcutWithRetry(runtime: Runtime) -> Bool {
        for (attemptIndex, delay) in runtime.pasteRetryBackoff.enumerated() {
            if delay > 0 {
                Thread.sleep(forTimeInterval: delay)
            }

            if runtime.sendSpecialPaste() {
                if attemptIndex > 0 {
                    runtime.log("Special paste shortcut succeeded on retry \(attemptIndex + 1)")
                }
                return true
            }
        }

        return false
    }

    @MainActor
    private static func makeLiveRuntime(typingStrategy: TypingStrategy) -> Runtime {
        Runtime(
            shouldTryDirectInsert: {
                shouldTryDirectInsertForFrontmostApp()
            },
            insertDirect: { text in
                insertDirectlyIntoFocusedTextInput(text)
            },
            insertTyping: { text in
                insertByTyping(text, strategy: typingStrategy)
            },
            writeClipboard: { text in
                verifiedClipboardWrite(text)
            },
            writeTransientClipboard: { text in
                verifiedClipboardWrite(text, useTransientMetadata: true)
            },
            sendSpecialPaste: {
                sendSpecialPasteShortcutOnce()
            },
            captureClipboard: {
                capturePasteboardSnapshot()
            },
            restoreClipboard: { snapshot, changeCount in
                restorePasteboardSnapshot(snapshot, expectedChangeCount: changeCount)
            },
            log: { message in
                logger.debug("\(message, privacy: .public)")
            }
        )
    }

    @MainActor
    private static func verifiedClipboardWrite(_ text: String, useTransientMetadata: Bool = false) -> ClipboardWriteOutcome {
        let pasteboard = NSPasteboard.general
        var lastFailure = "clipboard-write-rejected"

        for delay in clipboardWriteRetryBackoff {
            if delay > 0 {
                Thread.sleep(forTimeInterval: delay)
            }

            let beforeChangeCount = pasteboard.changeCount
            pasteboard.clearContents()

            let wroteString: Bool
            if useTransientMetadata {
                wroteString = writePasteboardItemWithMetadata(text: text, pasteboard: pasteboard)
            } else {
                wroteString = pasteboard.setString(text, forType: .string)
            }

            guard wroteString else {
                lastFailure = "clipboard-write-rejected"
                continue
            }

            let afterChangeCount = pasteboard.changeCount
            guard pasteboard.string(forType: .string) == text else {
                lastFailure = "clipboard-readback-mismatch"
                continue
            }

            guard afterChangeCount != beforeChangeCount else {
                lastFailure = "clipboard-change-count-stale"
                continue
            }

            return .success(changeCount: afterChangeCount)
        }

        return .failure(debugStatus: lastFailure)
    }

    @MainActor
    private static func writePasteboardItemWithMetadata(text: String, pasteboard: NSPasteboard) -> Bool {
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else {
            return false
        }

        // These metadata types signal to clipboard managers that this pasteboard entry is transient/sensitive.
        // Managers that honor these tags should avoid storing it in persistent history.
        for markerType in transientPasteboardTypes {
            _ = item.setData(Data(), forType: markerType)
        }
        _ = item.setData(Data(), forType: openAssistTransientMarkerType)

        return pasteboard.writeObjects([item])
    }

    @MainActor
    private static func capturePasteboardSnapshot() -> ClipboardSnapshot {
        let snapshotItems = NSPasteboard.general.pasteboardItems?.compactMap { item -> ClipboardSnapshot.Item? in
            let representations = item.types.compactMap { type -> ClipboardSnapshot.Item.Representation? in
                guard let data = item.data(forType: type) else {
                    return nil
                }
                return ClipboardSnapshot.Item.Representation(type: type, data: data)
            }

            guard !representations.isEmpty else {
                return nil
            }

            return ClipboardSnapshot.Item(representations: representations)
        } ?? []

        return ClipboardSnapshot(items: snapshotItems)
    }

    @MainActor
    private static func restorePasteboardSnapshot(_ snapshot: ClipboardSnapshot, expectedChangeCount: Int) {
        let pasteboard = NSPasteboard.general
        let savedItems = snapshot.items

        DispatchQueue.main.asyncAfter(deadline: .now() + clipboardRestoreDelay) {
            let changeCountMatches = pasteboard.changeCount == expectedChangeCount
            let stillHasTransientMarker = pasteboardContainsTransientMarker(pasteboard)
            guard changeCountMatches || stillHasTransientMarker else {
                return
            }

            pasteboard.clearContents()

            let restoredItems = savedItems.compactMap { snapshotItem -> NSPasteboardItem? in
                let restoredItem = NSPasteboardItem()
                var hasRepresentation = false

                for representation in snapshotItem.representations {
                    if restoredItem.setData(representation.data, forType: representation.type) {
                        hasRepresentation = true
                    }
                }

                return hasRepresentation ? restoredItem : nil
            }

            if !restoredItems.isEmpty, !pasteboard.writeObjects(restoredItems) {
                logger.debug("Pasteboard restore writeObjects failed")
            }
        }
    }

    @MainActor
    private static func pasteboardContainsTransientMarker(_ pasteboard: NSPasteboard) -> Bool {
        guard let items = pasteboard.pasteboardItems else {
            return false
        }

        for item in items {
            if item.availableType(from: [openAssistTransientMarkerType]) != nil {
                return true
            }
        }

        return false
    }

    @MainActor
    private static func liveTypingStrategy(for insertionContext: InsertionContext) -> TypingStrategy {
        typingStrategy(
            forFrontmostBundleIdentifier: NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
            insertionContext: insertionContext
        )
    }

    static func typingStrategy(
        forFrontmostBundleIdentifier bundleIdentifier: String?,
        insertionContext: InsertionContext
    ) -> TypingStrategy {
        guard insertionContext == .dictation else {
            return .unicodeEvents
        }

        if normalizedBundleIdentifier(bundleIdentifier) == "com.microsoft.rdc.macos" {
            return .appleScriptKeystrokePreferred
        }

        return .unicodeEvents
    }

    @MainActor
    private static func liveInsertionPolicy(for insertionContext: InsertionContext) -> InsertionPolicy {
        insertionPolicy(
            forFrontmostBundleIdentifier: NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
            insertionContext: insertionContext
        )
    }

    static func insertionPolicy(
        forFrontmostBundleIdentifier bundleIdentifier: String?,
        insertionContext: InsertionContext
    ) -> InsertionPolicy {
        guard insertionContext == .dictation else {
            return .standard
        }

        if normalizedBundleIdentifier(bundleIdentifier) == "com.microsoft.rdc.macos" {
            return .preferTypingFirst
        }

        return .standard
    }

    private static func normalizedBundleIdentifier(_ bundleIdentifier: String?) -> String? {
        guard let bundleIdentifier else {
            return nil
        }

        let normalized = bundleIdentifier
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()

        return normalized.isEmpty ? nil : normalized
    }

    @MainActor
    private static func shouldTryDirectInsertForFrontmostApp() -> Bool {
        // AX value mutations are app-specific and can duplicate text or preserve placeholder artifacts
        // in modern web/AI shells. Default to paste/typing paths unless explicitly opted in.
        guard ProcessInfo.processInfo.environment["OPENASSIST_ENABLE_AX_DIRECT_INSERT"] == "1" else {
            return false
        }

        guard let bundleIdentifier = NSWorkspace.shared.frontmostApplication?.bundleIdentifier?.lowercased() else {
            return true
        }

        let bypassPrefixes: [String] = [
            "com.apple.terminal",
            "com.googlecode.iterm2",
            "com.microsoft.vscode",
            "com.vscodium",
            "com.todesktop.230313mzl4w4u92", // Cursor
            "com.jetbrains."
        ]

        for prefix in bypassPrefixes where bundleIdentifier.hasPrefix(prefix) {
            return false
        }

        return true
    }

    private static func sendSpecialPasteShortcutOnce() -> Bool {
        debugLog("sendPaste: trying menu-item paste first")
        if sendPasteViaMenuItemAppleScript() {
            debugLog("sendPaste: menu-item paste succeeded")
            return true
        }

        debugLog("sendPaste: menu-item paste unavailable, trying AppleScript keystroke")
        if sendPasteViaAppleScriptKeystroke() {
            debugLog("sendPaste: AppleScript keystroke succeeded")
            return true
        }
        debugLog("sendPaste: AppleScript keystroke failed, trying CGEvent")

        let source = CGEventSource(stateID: .combinedSessionState) ?? CGEventSource(stateID: .hidSystemState)
        guard let source else {
            debugLog("sendPaste: CGEventSource creation FAILED")
            return false
        }

        let commandKeyCode: CGKeyCode = 55 // Left Command
        let vKeyV: CGKeyCode = 9 // kVK_ANSI_V

        guard
            let commandDown = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: true),
            let commandUp = CGEvent(keyboardEventSource: source, virtualKey: commandKeyCode, keyDown: false),
            let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyV, keyDown: true),
            let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyV, keyDown: false)
        else {
            return false
        }

        Thread.sleep(forTimeInterval: 0.03)

        commandDown.post(tap: .cgSessionEventTap)
        Thread.sleep(forTimeInterval: 0.004)

        keyDown.flags = [.maskCommand]
        keyDown.post(tap: .cgSessionEventTap)

        keyUp.flags = [.maskCommand]
        keyUp.post(tap: .cgSessionEventTap)

        Thread.sleep(forTimeInterval: 0.004)
        commandUp.post(tap: .cgSessionEventTap)

        Thread.sleep(forTimeInterval: 0.01)

        return true
    }

    private static func sendPasteViaMenuItemAppleScript() -> Bool {
        let script = NSAppleScript(source: """
            tell application "System Events"
                tell first application process whose frontmost is true
                    click menu item "Paste" of menu 1 of menu bar item "Edit" of menu bar 1
                end tell
            end tell
            """)
        var error: NSDictionary?
        script?.executeAndReturnError(&error)
        return error == nil
    }

    private static func sendPasteViaAppleScriptKeystroke() -> Bool {
        let script = NSAppleScript(source: """
            tell application "System Events"
                keystroke "v" using command down
            end tell
            """)
        var error: NSDictionary?
        script?.executeAndReturnError(&error)
        return error == nil
    }

    // Non-clipboard fallback: types text directly into the focused field.
    private static func insertByTyping(_ text: String, strategy: TypingStrategy) -> Bool {
        if strategy == .appleScriptKeystrokePreferred {
            debugLog("typing: trying AppleScript keystroke path first")
            if insertByAppleScriptKeystroke(text) {
                debugLog("typing: AppleScript keystroke path SUCCEEDED")
                return true
            }
            debugLog("typing: AppleScript keystroke path FAILED, falling back to unicode events")
        }

        return insertByUnicodeEvents(text)
    }

    private static func insertByUnicodeEvents(_ text: String) -> Bool {
        let source = CGEventSource(stateID: .combinedSessionState) ?? CGEventSource(stateID: .hidSystemState)
        guard let source else {
            return false
        }

        for scalar in text.unicodeScalars {
            if scalar.value == 10 {
                guard
                    let returnDown = CGEvent(keyboardEventSource: source, virtualKey: 36, keyDown: true),
                    let returnUp = CGEvent(keyboardEventSource: source, virtualKey: 36, keyDown: false)
                else {
                    return false
                }
                returnDown.post(tap: .cgSessionEventTap)
                returnUp.post(tap: .cgSessionEventTap)
                continue
            }

            var utf16Units = Array(String(scalar).utf16)
            guard
                let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true),
                let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
            else {
                return false
            }

            keyDown.keyboardSetUnicodeString(stringLength: utf16Units.count, unicodeString: &utf16Units)
            keyUp.keyboardSetUnicodeString(stringLength: utf16Units.count, unicodeString: &utf16Units)

            keyDown.post(tap: .cgSessionEventTap)
            keyUp.post(tap: .cgSessionEventTap)
        }

        return true
    }

    private static func insertByAppleScriptKeystroke(_ text: String) -> Bool {
        let normalized = text
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")

        var currentChunk = ""

        func flushChunk() -> Bool {
            guard !currentChunk.isEmpty else { return true }
            let escaped = appleScriptEscaped(currentChunk)
            let script = NSAppleScript(source: """
                tell application "System Events"
                    keystroke "\(escaped)"
                end tell
                """)
            var error: NSDictionary?
            script?.executeAndReturnError(&error)
            let succeeded = error == nil
            if !succeeded, let error {
                debugLog("typing: AppleScript keystroke error \(error)")
            }
            currentChunk = ""
            return succeeded
        }

        func sendSpecialKeyCode(_ keyCode: Int) -> Bool {
            let script = NSAppleScript(source: """
                tell application "System Events"
                    key code \(keyCode)
                end tell
                """)
            var error: NSDictionary?
            script?.executeAndReturnError(&error)
            let succeeded = error == nil
            if !succeeded, let error {
                debugLog("typing: AppleScript key code error \(error)")
            }
            return succeeded
        }

        for scalar in normalized.unicodeScalars {
            switch scalar.value {
            case 10:
                guard flushChunk(), sendSpecialKeyCode(36) else {
                    return false
                }
            case 9:
                guard flushChunk(), sendSpecialKeyCode(48) else {
                    return false
                }
            default:
                currentChunk.unicodeScalars.append(scalar)
                if currentChunk.count >= 48, !flushChunk() {
                    return false
                }
            }
        }

        return flushChunk()
    }

    private static func appleScriptEscaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    // Tries to insert/replace text in the currently focused element via Accessibility.
    private static func insertDirectlyIntoFocusedTextInput(_ text: String) -> Bool {
        guard let focusedElement = focusedTextElement() else {
            return false
        }

        guard let rawCurrentValue = stringAttributeValue(for: focusedElement, attribute: kAXValueAttribute as CFString) else {
            return false
        }
        let placeholderValue = stringAttributeValue(for: focusedElement, attribute: kAXPlaceholderValueAttribute as CFString)
        let currentValue = valueByRemovingPlaceholderArtifacts(
            rawCurrentValue,
            placeholderValue: placeholderValue
        )

        var selectedRangeRef: CFTypeRef?
        let rangeResult = AXUIElementCopyAttributeValue(
            focusedElement,
            kAXSelectedTextRangeAttribute as CFString,
            &selectedRangeRef
        )
        guard rangeResult == .success, let selectedRangeRef else {
            return false
        }

        guard CFGetTypeID(selectedRangeRef) == AXValueGetTypeID() else {
            return false
        }

        let selectedRangeAX = unsafeBitCast(selectedRangeRef, to: AXValue.self)
        guard AXValueGetType(selectedRangeAX) == .cfRange else {
            return false
        }

        var selectedRange = CFRange(location: 0, length: 0)
        guard AXValueGetValue(selectedRangeAX, .cfRange, &selectedRange) else {
            return false
        }

        let currentNSString = currentValue as NSString
        let safeLocation = max(0, min(selectedRange.location, currentNSString.length))
        let safeLength = max(0, min(selectedRange.length, currentNSString.length - safeLocation))
        let replacementRange = NSRange(location: safeLocation, length: safeLength)
        let updatedValue = currentNSString.replacingCharacters(in: replacementRange, with: text)

        let setValueResult = AXUIElementSetAttributeValue(
            focusedElement,
            kAXValueAttribute as CFString,
            updatedValue as CFTypeRef
        )
        guard setValueResult == .success else {
            return false
        }

        if let verifiedValue = stringAttributeValue(for: focusedElement, attribute: kAXValueAttribute as CFString) {
            let normalizedVerifiedValue = valueByRemovingPlaceholderArtifacts(
                verifiedValue,
                placeholderValue: placeholderValue
            )
            if normalizedVerifiedValue == currentValue {
                return false
            }
        }

        var newSelection = CFRange(location: safeLocation + (text as NSString).length, length: 0)
        if let newSelectionAX = AXValueCreate(.cfRange, &newSelection) {
            _ = AXUIElementSetAttributeValue(
                focusedElement,
                kAXSelectedTextRangeAttribute as CFString,
                newSelectionAX
            )
        }

        return true
    }

    private static func stringAttributeValue(for element: AXUIElement, attribute: CFString) -> String? {
        var valueRef: CFTypeRef?
        let result = AXUIElementCopyAttributeValue(element, attribute, &valueRef)
        guard result == .success, let value = valueRef as? String else {
            return nil
        }
        return value
    }

    private static func valueByRemovingPlaceholderArtifacts(_ value: String, placeholderValue: String?) -> String {
        guard let placeholderValue = placeholderValue?.trimmingCharacters(in: .whitespacesAndNewlines),
              !placeholderValue.isEmpty else {
            return value
        }

        if value == placeholderValue {
            return ""
        }

        let suffixCandidates = [
            placeholderValue,
            " " + placeholderValue,
            "\n" + placeholderValue,
            "\t" + placeholderValue
        ]

        for suffix in suffixCandidates where value.hasSuffix(suffix) {
            return String(value.dropLast(suffix.count))
        }

        let prefixCandidates = [
            placeholderValue,
            placeholderValue + " ",
            placeholderValue + "\n",
            placeholderValue + "\t"
        ]

        for prefix in prefixCandidates where value.hasPrefix(prefix) {
            return String(value.dropFirst(prefix.count))
        }

        return value
    }

    private static func focusedTextElement() -> AXUIElement? {
        let systemWide = AXUIElementCreateSystemWide()
        var focusedRef: CFTypeRef?
        let focusedResult = AXUIElementCopyAttributeValue(
            systemWide,
            kAXFocusedUIElementAttribute as CFString,
            &focusedRef
        )
        guard focusedResult == .success, let focusedRef else {
            return nil
        }

        guard CFGetTypeID(focusedRef) == AXUIElementGetTypeID() else {
            return nil
        }

        return unsafeBitCast(focusedRef, to: AXUIElement.self)
    }

    private static func resultLabel(_ result: Result) -> String {
        switch result {
        case .pasted:
            return "pasted"
        case .copiedOnly:
            return "copiedOnly"
        case .notInserted:
            return "notInserted"
        case .empty:
            return "empty"
        }
    }
}
